added flash sh file

diff --git a/Dockerfile.espressif b/Dockerfile.espressif
--- a/Dockerfile.espressif
+++ b/Dockerfile.espressif
@@ -4,8 +4,8 @@
 ARG DEBIAN_VERSION=stable-20241016-slim
 ARG PASSWORD="zephyr"
 # Zephyr 3.7.0 is not working with ESP32S3, see: https://github.com/zephyrproject-rtos/zephyr/issues/71397
-ARG ZEPHYR_RTOS_VERSION=4.3.0
-ARG ZEPHYR_RTOS_COMMIT=v4.3.0
+#ARG ZEPHYR_RTOS_VERSION=3.7.0
+ARG ZEPHYR_RTOS_COMMIT=26603cefaf41298c417f2eee834ed40d9ab35d3a
 ARG ZEPHYR_SDK_VERSION=0.16.8
 ARG TOOLCHAIN_LIST="-t xtensa-espressif_esp32_zephyr-elf -t xtensa-espressif_esp32s2_zephyr-elf -t xtensa-espressif_esp32s3_zephyr-elf"
 ARG WGET_ARGS="-q --show-progress --progress=bar:force:noscroll"
@@ -22,12 +22,6 @@ ARG PASSWORD
 ARG ZEPHYR_RTOS_VERSION
 ARG ZEPHYR_RTOS_COMMIT
 ARG ZEPHYR_SDK_VERSION
-ARG VS_CODE_SERVER_VERSION
-ARG VS_CODE_SERVER_PORT
-ARG VS_CODE_EXT_CPPTOOLS_VERSION
-ARG VS_CODE_EXT_HEX_EDITOR_VERSION
-ARG VS_CODE_EXT_CMAKETOOLS_VERSION
-ARG VS_CODE_EXT_NRF_DEVICETREE_VERSION
 ARG TOOLCHAIN_LIST
 ARG WGET_ARGS
 ARG VIRTUAL_ENV
@@ -38,10 +32,10 @@ SHELL ["/bin/bash", "-c"]
 
 # Check if the target architecture is either x86_64 (amd64) or arm64 (aarch64)
 RUN if [ "$TARGETARCH" = "amd64" ] || [ "$TARGETARCH" = "arm64" ]; then \
-    echo "Architecture $TARGETARCH is supported."; \
+        echo "Architecture $TARGETARCH is supported."; \
     else \
-    echo "Unsupported architecture: $TARGETARCH"; \
-    exit 1; \
+        echo "Unsupported architecture: $TARGETARCH"; \
+        exit 1; \
     fi
 
 # Set non-interactive frontend for apt-get to skip any user confirmations
@@ -50,28 +44,26 @@ ENV DEBIAN_FRONTEND=noninteractive
 # Install base packages
 RUN apt-get -y update && \
     apt-get install --no-install-recommends -y \
-    dos2unix \
-    ca-certificates \
-    file \
-    locales \
-    git \
-    build-essential \
-    cmake \
-    ninja-build gperf \
-    device-tree-compiler \
-    wget \
-    curl \
-    python3 \
-    python3-pip \
-    python3-venv \
-    xz-utils \
-    dos2unix \
-    vim \
-    nano \
-    mc \
-    openssh-server \
-    libusb-1.0-0
-
+        dos2unix \
+        ca-certificates \
+        file \
+        locales \
+        git \
+        build-essential \
+        cmake \
+        ninja-build gperf \
+        device-tree-compiler \
+        wget \
+        curl \
+        python3 \
+        python3-pip \
+        python3-venv \
+        xz-utils \
+        dos2unix \
+        vim \
+        nano \
+        mc \
+        openssh-server
 
 # Set root password
 RUN echo "root:${PASSWORD}" | chpasswd
@@ -152,21 +144,50 @@ RUN cd /opt/toolchains/zephyr-sdk-${ZEPHYR_SDK_VERSION} && \
     rm hosttools_linux-${HOSTTYPE}.tar.xz && \
     bash zephyr-sdk-${HOSTTYPE}-hosttools-standalone-*.sh -y -d .
 
+#-------------------------------------------------------------------------------
+# VS Code Server
 
+# Set VS Code Server environment variables
+ENV VS_CODE_SERVER_VERSION=${VS_CODE_SERVER_VERSION}
+ENV VS_CODE_SERVER_PORT=${VS_CODE_SERVER_PORT}
 
-    #-------------------------------------------------------------------------------
-# Espressif IDF (Optional, alongside Zephyr)
+# # Install VS Code Server
+# RUN cd /tmp && \
+#     wget ${WGET_ARGS} https://code-server.dev/install.sh && \
+#     chmod +x install.sh && \
+#     bash install.sh --version ${VS_CODE_SERVER_VERSION}
 
-ARG ESP_IDF_VERSION=v5.4.2
-ENV IDF_PATH=/opt/toolchains/esp-idf
+# # Download VS Code extensions (code-server extension manager does not work well)
+# RUN cd /tmp && \
+#     if [ "$TARGETARCH" = "amd64" ]; then \
+#         wget ${WGET_ARGS} https://github.com/microsoft/vscode-cpptools/releases/download/v${VS_CODE_EXT_CPPTOOLS_VERSION}/cpptools-linux-x64.vsix -O cpptools.vsix; \
+#     elif [ "$TARGETARCH" = "arm64" ]; then \
+#         wget ${WGET_ARGS} https://github.com/microsoft/vscode-cpptools/releases/download/v${VS_CODE_EXT_CPPTOOLS_VERSION}/cpptools-linux-arm64.vsix -O cpptools.vsix; \
+#     else \
+#         echo "Unsupported architecture"; \
+#         exit 1; \
+#     fi && \
+#     wget ${WGET_ARGS} https://github.com/microsoft/vscode-cmake-tools/releases/download/v${VS_CODE_EXT_CMAKETOOLS_VERSION}/cmake-tools.vsix -O cmake-tools.vsix && \
+#     wget --compression=gzip ${WGET_ARGS} https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/hexeditor/${VS_CODE_EXT_HEX_EDITOR_VERSION}/vspackage -O hexeditor.vsix && \
+#     wget --compression=gzip https://marketplace.visualstudio.com/_apis/public/gallery/publishers/nordic-semiconductor/vsextensions/nrf-devicetree/${VS_CODE_EXT_NRF_DEVICETREE_VERSION}/vspackage -O nordic-semiconductor.nrf-devicetree.vsix
 
-# Install Espressif IDF
-RUN cd /opt/toolchains && \
-    git clone --depth 1 -b ${ESP_IDF_VERSION} https://github.com/espressif/esp-idf.git && \
-    cd esp-idf && \
-    unset VIRTUAL_ENV && \
-    export PATH=$(echo "$PATH" | sed -e "s|${VIRTUAL_ENV}/bin:||") && \
-    ./install.sh esp32s3
+# # Install extensions
+# RUN cd /tmp && \
+#     code-server --install-extension cpptools.vsix && \
+#     code-server --install-extension cmake-tools.vsix && \
+#     code-server --install-extension hexeditor.vsix && \
+#     code-server --install-extension nordic-semiconductor.nrf-devicetree.vsix
+
+# Clean up
+RUN cd /tmp && \
+    rm -rf install.sh && \
+    rm -rf cpptools.vsix && \
+    rm -rf cmake-tools.vsix && \
+    rm -rf hexeditor.vsix && \
+    rm -rf nordic-semiconductor.nrf-devicetree.vsix
+
+# Copy workspace configuration
+COPY scripts/zephyr.code-workspace /zephyr.code-workspace
 
 #-------------------------------------------------------------------------------
 # Optional Settings
@@ -184,6 +205,10 @@ ENV MC_SKIN=dark
 
 # Activate the Python and Zephyr environments for shell sessions
 RUN echo "source ${VIRTUAL_ENV}/bin/activate" >> /root/.bashrc && \
-    echo "source /opt/toolchains/zephyr/zephyr-env.sh" >> /root/.bashrc && \
-    echo "source ${IDF_PATH}/export.sh" >> /root/.bashrc
+    echo "source /opt/toolchains/zephyr/zephyr-env.sh" >> /root/.bashrc
 
+# # Custom entrypoint
+# COPY scripts/entrypoint.sh /entrypoint.sh
+# RUN chmod +x /entrypoint.sh && \
+#     dos2unix /entrypoint.sh
+# ENTRYPOINT ["/entrypoint.sh"]
